export interface Contact {
  'E-mail Address': String;
  'Related name': String;
  'Home Address 2': String;
  Anniversary: String;
  'First Name': String;
  'Business Address 2': String;
  Department: String;
  'Display Name': String;
  'Home State': String;
  'Business Country': String;
  'Home Street': String;
  Birthday: String;
  'Home Country': String;
  Pager: String;
  Categories: String;
  'Home City': String;
  'E-mail 3 Address': String;
  'Home Fax': String;
  Gender: String;
  Notes: String;
  'Country Code': String;
  'Job Title': String;
  'Business Address': String;
  'Web Page 2': String;
  'Mobile Phone': String;
  Organization: String;
  'Home Phone': String;
  'E-mail 2 Address': String;
  'Last Name': String;
  Nickname: String;
  'Business Fax': String;
  'Home Postal Code': String;
  'Business Phone': String;
  'Business Postal Code': String;
  'Web Page': String;
  'Business City': String;
  'Business State': String;
}
